### ISSUE TITLE
Bug: iquote in copts are not handled correctly

### ISSUE THREAD

**Issue by xinzhengzhang** [buildbuddy-io/rules_xcodeproj#1809] opened 2023-03-06 12:11 UTC
## Describe the bug
Xcode cannot jump to definition which needs path defined in iquote.
It looks like the file jump behavior doesn't go through the XCBuildServiceProxy, may be we should parse it into `HEADER_SEARCH_PATH`

## Reproduction steps
```
#Directory structure
- srcs
    - module_a
        - a.m
            - #import "b.h"
    - module_b
        - b.h
```
```
objc_library(
    name = "lib",
    srcs = ["srcs/module_a/a.m"],
    copts = [
        "-iquote srcs/module_b",
    ],
)
```

## Expected behavior
Xcode correctly jumps to imported files

## Versions
- Bazel: 6.0.0
- rules_xcodeproj: 1.2.0
- rules_apple: 2.0.0
- rules_swift: 1.6.0

## Additional context
I tried to implement it, and it worked fine in my project.
```
diff --git a/tools/generator/src/Generator/SetTargetConfigurations.swift b/tools/generator/src/Generator/SetTargetConfigurations.swift
index 74bce49a..8abf7225 100644
--- a/tools/generator/src/Generator/SetTargetConfigurations.swift
+++ b/tools/generator/src/Generator/SetTargetConfigurations.swift
@@ -432,7 +432,17 @@ $(CONFIGURATION_BUILD_DIR)
             buildSettings["OTHER_CPLUSPLUSFLAGS"] =
                 "$(ASAN_OTHER_CPLUSPLUSFLAGS__$(CLANG_ADDRESS_SANITIZER))"
         }
-
+        if let settings = buildSettings["OTHER_CFLAGS"], let cFlags = settings.asAny as? [String] {
+            let iquotes = cFlags.filter { $0.starts(with: "\"-iquote ") && $0.hasSuffix("\"")}
+            if iquotes.count > 0 {
+                buildSettings["HEADER_SEARCH_PATHS"] = BuildSetting.array(iquotes.map {
+                    // 9 characters("-iquote ) which start with " end with space
+                    let startIndex = $0.index($0.startIndex, offsetBy: 8)
+                    let endIndex = $0.index($0.endIndex, offsetBy: -1)
+                    return String($0[startIndex..<endIndex])
+                })
+            }
+        }
```

**Comment by brentleyjones** [comment] 2023-03-06 14:10
We moved away from parsing copts, and removed setting of header search paths, to have better compatibility with multiple rulesets. I'll look at this bug more, but I would assume anything set via `OTHER_CFLAGS` would work for indexing as well, because in the end all of them are sent to clang or SourceKit.

Can you create an actual reproduction project that shows this incorrect behavior? I want to make sure I see the before and after behavior correctly before deciding one way or another on a fix. Thanks.

**Comment by xinzhengzhang** [comment] 2023-03-07 08:33
> Also, can you elaborate on the exact steps in Xcode you take for this?
> 
> > Xcode correctly jumps to imported files

Sure, I pushed a sample project https://github.com/xinzhengzhang/iquote-sample
And the screen recording shows how the problem reproduces https://github.com/xinzhengzhang/iquote-sample/blob/main/issue.mov

**Comment by brentleyjones** [comment] 2023-03-07 14:22
The issue is that you are passing a single copt, when it should be two, or no space. So one of these works:

```
copts = [
    "-iquotesrcs/module_a/sub_module_b",
]
```

```
copts = [
    "-iquote","
    "srcs/module_a/sub_module_b",
]
```

Now, I realize bazel works with the version you used, so I'll try to make this work with rules_xcodeproj as well, without breaking other quoting functionality.

**Comment by xinzhengzhang** [comment] 2023-03-07 15:29
Thanks for helping me correct the way that how iquote should be used and I will fix it in my project.
Do I need to close this issue or do you close it after being compatible with this non-standard way of  iquote?

**Comment by brentleyjones** [comment] 2023-03-07 16:59
I'll close it once I fix it on our side. We should support this. The main issue is that we quote things differently than bazel, and I want to fix that misalignment.

**Closed** 2023-03-07 21:59 UTC
Labels: bug

**Comment by brentleyjones** [comment] 2023-03-07 22:51
If you check with the latest on `main`, this should be fixed now.
