### ISSUE TITLE
Bug: building swiftc_stub.library fails

### ISSUE THREAD

**Issue by jfirebaugh** [buildbuddy-io/rules_xcodeproj#1424] opened 2022-11-09 02:20 UTC
## Describe the bug
`bazel run :xcodeproj` fails with the following error:

```
ERROR: /private/var/tmp/_bazel_john/67beefda950d56283b98d96980e6e332/rules_xcodeproj/build_output_base/external/com_github_buildbuddy_io_rules_xcodeproj/tools/swiftc_stub/BUILD:26:14: Compiling Swift module @com_github_buildbuddy_io_rules_xcodeproj//tools/swiftc_stub:swiftc_stub.library failed: (Exit 86): worker failed: error executing command 
  (cd /private/var/tmp/_bazel_john/67beefda950d56283b98d96980e6e332/rules_xcodeproj/build_output_base/execroot/figma && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=12.3 \
    SWIFT_AVOID_WARNING_USING_OLD_DRIVER=1 \
    XCODE_VERSION_OVERRIDE=14.0.0.14A309 \
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-8ea46ebbd87a/bin/external/build_bazel_rules_swift/tools/worker/worker swiftc @bazel-out/macos-x86_64-min12.0-applebin_macos-darwin_x86_64-opt-exec-2B5CBBC6-ST-53a59ce00716/bin/external/com_github_buildbuddy_io_rules_xcodeproj/tools/swiftc_stub/tools_swiftc_stub_swiftc_stub_library.swiftmodule-0.params)
```

## Reproduction steps

https://github.com/jfirebaugh/rules_xcode_reduction/tree/1424

## Expected behavior

`bazel run :xcodeproj` succeeds. 

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: 0.10.2
- rules_apple: as installed by `apple_rules_dependencies()`
- rules_swift: as installed by `swift_rules_dependencies()`

**Comment by brentleyjones** [comment] 2022-11-09 03:00
The issue is rules_swift's index_import is currently using an x86_64 binary, and rosetta wasn't installed. I'll bump the dependency in rules_swift to get this fixed in the near future.

**Comment by brentleyjones** [comment] 2022-11-09 03:03
https://github.com/bazelbuild/rules_swift/pull/932

**Comment by brentleyjones** [comment] 2022-11-09 03:16
So not exactly an issue with rules_xcoderproj. I'll close this issue, but you can follow along in the linked issue above for when this is fixed on the rules_swift side, and when there is a release made after that fix lands, then I'll update our dependency as well.

**Closed by brentleyjones** 2022-11-09 03:16 UTC
Labels: bug
